version: '1'
services:
#  configserver:
#    image: johncarnell/tmx-confsvr:chapter3
#    ports:
#       - "8888:8888"
#    environment:
#      ENCRYPT_KEY:       "IMSYMMETRIC"
#  database:
#    image: postgres:9.5
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_USER: "postgres"
#      POSTGRES_PASSWORD: "p0stgr@s"
#      POSTGRES_DB:       "eagle_eye_local"
  mainservice:
    image: jspringio/simple_boot_docker
    ports:
      - "8080:8080"
  nameservice:
    image: springio/simple_boot_name
    ports:
      - "8082:8082"
#    environment:
#      PROFILE: "default"
#      CONFIGSERVER_URI: "http://configserver:8888"
#      CONFIGSERVER_PORT:   "8888"
#      DATABASESERVER_PORT: "5432"
#      ENCRYPT_KEY:       "IMSYMMETRIC"
